Completed node-require
macyhongg/mod2-0822-code-solutions pull request #18
Opened 2022-10-04 04:16 UTC by macyhongg

<img width="966" alt="image" src="https://user-images.githubusercontent.com/94674653/193733110-434bf4e9-0ad1-4be4-9483-113a2eb64791.png">

2022-10-04 04:19 UTC, TimelikeClosure requested changes

2022-10-04 04:19 UTC, TimelikeClosure commented on node-require/calculate.js
> +}
Each math operation should produce the correct output for all numbers, not just integers.

2022-10-05 01:57 UTC, macyhongg commented
<img width="986" alt="image" src="https://user-images.githubusercontent.com/94674653/193962879-89d9f949-8ae0-4faf-830a-7e261e999246.png">

2022-10-05 01:57 UTC, TimelikeClosure approved these changes

2022-10-05 01:57 UTC, merged